            $('#tbl_terapias').bootstrapTable({
                        method: 'get',
                        url: 'sh_terapias.php',
                        cache: false,
                        striped: true,
                        pagination: false,
                        search: true,
                        showColumns: true,
                        showRefresh: true,
                        showToggle: true,
                        minimumCountColumns: 4,
                        height: 300,
                        clickToSelect: false,
                        columns: [{
                            field: 'user_matricula',
                            title: 'Matrícula',
                            align: 'center',
                            valign: 'middle',
                            sortable: true,
                            visible: true,
                        },{
                            field: 'hma_id',
                            title: 'Hermano Mayor',
                            align: 'center',
                            valign: 'middle',
                            sortable: true,
                            visible: true,
                        },{
                            field: 'hme_id',
                            title: 'Hermano Menor',
                            align: 'center',
                            valign: 'middle',
                            sortable: true,
                            visible: true,
                        },{
                            field: 'his_data',
                            title: 'Inicio terapia',
                            align: 'center',
                            valign: 'middle',
                            sortable: true,
                            visible: true,
                        },{
                            field: 'his_comentario',
                            title: 'Notas',
                            align: 'center',
                            valign: 'middle',
                            sortable: true,
                            visible: true,
                        }]
                    });
